### ISSUE TITLE
Remove whitespaces at the beginning or end of the search term.

### ISSUE THREAD

**Issue by krlosmederos** [ErneMiralles92/rest-countries-api-with-color-theme-switcher-master#1]
### Expected Behavior:

If I write in the country search bar: **  Chile** (with some whitespaces at the beginning or end) the country card must be shown.

### Current Behavior

Shown nothing.

### Possible Solution

Use the `trim()` method, [ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim). 

https://github.com/ErneMiralles92/rest-countries-api-with-color-theme-switcher-master/blob/f0688a9304512ee963ea1e67ecc7c10a4ab849d2/pages/index.vue#L72

**Comment by krlosmederos** [comment]
@ErneMiralles92 crazy car 🎉🚀

**Comment by ErneMiralles92** [comment]
> ### Expected Behavior:
> If I write in the country search bar: ** Chile** (with some whitespaces at the beginning or end) the country card must be shown.
> 
> ### Current Behavior
> Shown nothing.
> 
> ### Possible Solution
> Use the `trim()` method, [ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/Trim).
> 
> https://github.com/ErneMiralles92/rest-countries-api-with-color-theme-switcher-master/blob/f0688a9304512ee963ea1e67ecc7c10a4ab849d2/pages/index.vue#L72

Thanks, for the suggestions, the issue is already fix
